repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.2
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.7
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
